spring:
    datasource:
       url: jdbc:postgresql://localhost:5432/kitdm20
       username: jejkal
       password:
       driverClassName: org.postgresql.Driver
    jpa:
      database: POSTGRESQL
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      properties:
        #hibernate:
          #show_sql: true
          #use_sql_comments: true
          #format_sql: true
    servlet:
       # Max file size.
       multipart.max-file-size: 10MB
       # Max request size.
       multipart.max-request-size: 10MB

repo:
   auth:
      jwtSecret: test123
      enabled: false
   basepath:  file:///Users/jejkal/tmp 
   messaging:
      enabled: false 
      binding:
         exchange: repository_events
         queue: testQueue1
         routingKeys: dataresource.create.#, dataresource.update.#
   schedule:
      rate: 1000
management:
   endpoint:
      health:
         show-details: "ALWAYS"
         sensitive: false
      web:
      exposure:
          include: "*"
   security:
   enabled: false
logging:
   level:
      #root: TRACE
      edu.kit: TRACE
      org.springframework: TRACE
      org.springframework.amqp: DEBUG
server:
   port: 8090
#   compression:
#      enabled: false