spring:
    datasource:
       url: jdbc:postgresql://localhost:5432/kitdm20
       username: jejkal
       password:
       driverClassName: org.postgresql.Driver
    jpa:
      database: POSTGRESQL
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      properties:
        #hibernate:
          #show_sql: true
          #use_sql_comments: true
          #format_sql: true
    ################################################################################
    ###                  MAX file size for up-/download                          ###
    ################################################################################
    servlet:
      # Max file size. (Default 1MB)   
#      multipart.max-file-size: 10MB
      # Max request size. (Default 1MB)
#      multipart.max-request-size: 10MB
repo:
   auth:
      jwtSecret: test123
      enabled: false
   basepath:  file:///Users/jejkal/tmp 
   messaging:
      enabled: true 
      binding:
         exchange: repository_events
         queue: testQueue1
         routingKeys: dataresource.create.#, dataresource.update.#
   schedule:
      rate: 1000
management:
   endpoint:
      health:
         show-details: "ALWAYS"
         sensitive: false
      web:
      exposure:
          include: "*"
   security:
   enabled: false
logging:
   level:
      edu.kit: TRACE
      org.springframework: TRACE
      org.springframework.amqp: DEBUG
server:
   port: 8090
#   compression:
#      enabled: false
servlet:
    # Max file size.
    multipart.max-file-size: 10MB
    # Max request size.
    multipart.max-request-size: 10MB
